source 'https://rubygems.org'

# Specify your gem's dependencies in elasticsearch-transport.gemspec
gemspec

if File.exist? File.expand_path("../../elasticsearch2-api/elasticsearch-api.gemspec", __FILE__)
  gem 'elasticsearch2-api', :path => File.expand_path("../../elasticsearch2-api", __FILE__), :require => false
end

if File.exist? File.expand_path("../../elasticsearch2-extensions", __FILE__)
  gem 'elasticsearch2-extensions', :path => File.expand_path("../../elasticsearch2-extensions", __FILE__), :require => false
end

if File.exist? File.expand_path("../../elasticsearch2/elasticsearch.gemspec", __FILE__)
  gem 'elasticsearch2', :path => File.expand_path("../../elasticsearch2", __FILE__), :require => false
end
