source 'https://rubygems.org'

# Specify your gem's dependencies in elasticsearch.gemspec
gemspec

if File.exists? File.expand_path("../../elasticsearch2-api/elasticsearch-api.gemspec", __FILE__)
  gem 'elasticsearch2-api', :path => File.expand_path("../../elasticsearch2-api", __FILE__), :require => false
end

if File.exists? File.expand_path("../../elasticsearch2-transport/elasticsearch-transport.gemspec", __FILE__)
  gem 'elasticsearch2-transport', :path => File.expand_path("../../elasticsearch2-transport", __FILE__), :require => false
end

if File.exists? File.expand_path("../../elasticsearch2-extensions", __FILE__)
  gem 'elasticsearch2-extensions', :path => File.expand_path("../../elasticsearch2-extensions", __FILE__), :require => true
end
